version: "3.8"

services:
  noip:
    container_name: noip
    image: noip:latest
    networks:
      noip:
    volumes:
      - noip:/config
    restart: always

networks:
  noip:

volumes:
  noip:
    name: noip
